<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page import="com.fraudguard.model.FraudAlert" %>
<%@ page import="java.util.List" %>
<%@ page import="java.time.format.DateTimeFormatter" %>
<%
    request.setAttribute("pageTitle", "Analyst Fraud Triage Console");
    List<FraudAlert> alerts = (List<FraudAlert>) request.getAttribute("alerts");
    String selectedStatus = (String) request.getAttribute("selectedStatus");
    String cp = request.getContextPath();
    String msg = request.getParameter("msg");
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
%>
<jsp:include page="/views/common/header.jsp" />

<div class="page-header">
    <div>
        <h1 class="page-title">Fraud Investigation Triage Console</h1>
        <p class="page-subtitle">Security incidents generated by the FraudGuard AI Engine requiring human analyst disposition.</p>
    </div>
</div>

<% if ("status_updated".equals(msg)) { %>
    <div class="alert-box alert-success">
        <span>Fraud alert status and review notes successfully updated.</span>
    </div>
<% } %>

<!-- Filter Bar -->
<div class="card" style="margin-bottom: 1.5rem; padding: 1rem;">
    <form action="<%= cp %>/admin/alerts" method="get" style="display: flex; gap: 1rem; align-items: center; flex-wrap: wrap;">
        <label class="form-label" style="margin-bottom: 0;">Investigation State:</label>
        <select name="status" class="form-control" style="width: auto; min-width: 200px;">
            <option value="ALL" <%= "ALL".equals(selectedStatus) ? "selected" : "" %>>All Alert States</option>
            <option value="OPEN" <%= "OPEN".equals(selectedStatus) ? "selected" : "" %>>Open / Unassigned</option>
            <option value="UNDER_REVIEW" <%= "UNDER_REVIEW".equals(selectedStatus) ? "selected" : "" %>>Under Review</option>
            <option value="RESOLVED" <%= "RESOLVED".equals(selectedStatus) ? "selected" : "" %>>Resolved</option>
            <option value="DISMISSED" <%= "DISMISSED".equals(selectedStatus) ? "selected" : "" %>>Dismissed (False Positive)</option>
        </select>
        <button type="submit" class="btn btn-primary btn-sm">Filter</button>
        <a href="<%= cp %>/admin/alerts" class="btn btn-secondary btn-sm">Reset</a>
    </form>
</div>

<!-- Alerts Table with Inline Analyst Actions -->
<div class="card">
    <% if (alerts != null && !alerts.isEmpty()) { %>
        <div class="table-container">
            <table class="data-table responsive-card-table">
                <thead>
                    <tr>
                        <th>Alert ID</th>
                        <th>Created</th>
                        <th>User</th>
                        <th>Tx Reference</th>
                        <th>Amount</th>
                        <th>Risk Score</th>
                        <th>Triggered Rules / Reason</th>
                        <th>Current State</th>
                        <th>Analyst Action & Notes</th>
                    </tr>
                </thead>
                <tbody>
                    <% for (FraudAlert a : alerts) { 
                        String statusBadge = "badge-info";
                        if ("RESOLVED".equals(a.getStatus().name())) statusBadge = "badge-success";
                        else if ("UNDER_REVIEW".equals(a.getStatus().name())) statusBadge = "badge-warning";
                        else if ("OPEN".equals(a.getStatus().name())) statusBadge = "badge-danger";
                    %>
                        <tr>
                            <td data-label="Alert ID">#<%= a.getId() %></td>
                            <td data-label="Created"><%= a.getCreatedAt() != null ? a.getCreatedAt().format(dtf) : "—" %></td>
                            <td data-label="User">
                                <strong><%= a.getUserName() != null ? a.getUserName() : "User #" + a.getUserId() %></strong>
                            </td>
                            <td data-label="Tx Reference"><code><%= a.getTransactionRef() %></code></td>
                            <td data-label="Amount" style="font-weight: 700;">₹<%= String.format("%,.2f", a.getAmount()) %></td>
                            <td data-label="Risk Score">
                                <span class="badge <%= a.getRiskScore() >= 85 ? "badge-critical" : (a.getRiskScore() >= 60 ? "badge-danger" : "badge-warning") %>">
                                    <%= a.getRiskScore() %>/100 (<%= a.getRiskLevel().name() %>)
                                </span>
                            </td>
                            <td data-label="Rules & Reason" style="font-size: 0.82rem;">
                                <strong style="color: #fca5a5;"><%= a.getTriggeredRules() %></strong><br>
                                <span style="color: var(--text-secondary);"><%= a.getReason() %></span>
                            </td>
                            <td data-label="Current State">
                                <span class="badge <%= statusBadge %>"><%= a.getStatus().name() %></span><br>
                                <% if (a.getReviewedBy() != null) { %>
                                    <small style="color: var(--text-muted);">by <%= a.getReviewedBy() %></small>
                                <% } %>
                            </td>
                            <td data-label="Analyst Action">
                                <form action="<%= cp %>/admin/alert-action" method="post" style="display: flex; flex-direction: column; gap: 0.4rem; width: 100%;">
                                    <input type="hidden" name="alertId" value="<%= a.getId() %>">
                                    <div style="display: flex; gap: 0.35rem; width: 100%;">
                                        <select name="status" class="form-control" style="padding: 0.3rem 0.5rem; font-size: 0.8rem; flex: 1;">
                                            <option value="UNDER_REVIEW" <%= "UNDER_REVIEW".equals(a.getStatus().name()) ? "selected" : "" %>>Under Review</option>
                                            <option value="RESOLVED" <%= "RESOLVED".equals(a.getStatus().name()) ? "selected" : "" %>>Resolve (Verified)</option>
                                            <option value="DISMISSED" <%= "DISMISSED".equals(a.getStatus().name()) ? "selected" : "" %>>Dismiss (False Positive)</option>
                                        </select>
                                        <button type="submit" class="btn btn-primary btn-sm" style="padding: 0.3rem 0.75rem;">Save</button>
                                    </div>
                                    <input type="text" name="reviewNotes" class="form-control" style="padding: 0.3rem 0.5rem; font-size: 0.78rem; width: 100%;"
                                           placeholder="Resolution notes..." value="<%= a.getReviewNotes() != null ? a.getReviewNotes() : "" %>">
                                </form>
                            </td>
                        </tr>
                    <% } %>
                </tbody>
            </table>
        </div>
    <% } else { %>
        <div style="padding: 3rem; text-align: center; color: var(--text-muted);">
            No fraud alerts matching selected filter.
        </div>
    <% } %>
</div>

<jsp:include page="/views/common/footer.jsp" />
